### ISSUE TITLE
Complete documentation

### ISSUE THREAD

**Issue by dwijnand** [akka/akka-grpc-play-quickstart-java#25]

**Comment by ignasi35** [comment]
- [x] enabled paradox https://github.com/playframework/play-java-grpc-example/pull/30
- [x] x-ref akka-grcp docs on implementig a gRPC server https://github.com/playframework/play-java-grpc-example/pull/30
- [x] x-ref akka-grcp docs on using a gRPC client https://github.com/playframework/play-java-grpc-example/pull/30
- [x] explain HTTP/2+TLS when running locally https://github.com/playframework/play-java-grpc-example/pull/30
- [x] document specific settings (See https://github.com/playframework/play-scala-grpc-example/pull/28)

**Comment by dwijnand** [comment]
Awesome breakdown!
